# Generated by Django 3.2.4 on 2021-06-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makepayment',
            name='bank',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
