# Generated by Django 3.2.4 on 2021-06-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='makepayment',
            name='price',
            field=models.IntegerField(default=500),
        ),
    ]
