# Generated by Django 3.2.4 on 2021-06-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_makepayment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makepayment',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
