# Generated by Django 3.2.4 on 2021-06-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_makepayment_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makepayment',
            name='phone',
        ),
    ]
