# Generated by Django 3.2.4 on 2021-06-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_makepayment_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makepayment',
            name='email',
        ),
        migrations.AddField(
            model_name='makepayment',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
