# Generated by Django 3.2.4 on 2021-06-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20210602_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttoken',
            name='secret',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
